### ISSUE TITLE
もっと特徴量を増やす

### ISSUE THREAD

**Issue by reo11** [reo11/TMUProjectExpB1#17]
まだまだ足りないと思う

**Comment by ito-hiroki** [comment]
よしやるか

**Comment by ito-hiroki** [comment]
それぞれの部位(左右目、鼻、口、顔、左右眉、顎)の高さ、幅を出した
データはfeatures_basic.csv
それだけだとlightGBMの正解率が25%位

それを顔の幅で割った
データはfeatures_basic_divFaceWidth.csv
それで正解率が40%弱

**Comment by ito-hiroki** [comment]
それぞれの部位間の距離を出したら、まあまあの精度は出そう
